# Generated by Django 2.2 on 2023-01-12 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('author_type', models.CharField(choices=[('NOVELIST', 'Novelist'), ('POET', 'Poet'), ('JOURNALIST', 'Journalist')], default='NOVELIST', max_length=20)),
                ('lock_period', models.IntegerField(default=180)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('book_type', models.CharField(choices=[('PAPERBACK', 'Paperback'), ('HANDMADE', 'Handmade'), ('HARDCOVER', 'Hardcover')], default='PAPERBACK', max_length=20)),
                ('publisher', models.CharField(max_length=150)),
                ('no_of_copies', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('lock_period', models.IntegerField(default=90)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
