# Generated by Django 3.2.16 on 2023-01-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('author_type', models.CharField(choices=[('NOVELIST', 'Novelist'), ('POET', 'Poet'), ('JOURNALIST', 'Journalist')], default='NOVELIST', max_length=20)),
                ('lock_period', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('book_type', models.CharField(choices=[('PAPERBACK', 'Paperback'), ('HANDMADE', 'Handmade'), ('HARDCOVER', 'Hardcover')], default='PAPERBACK', max_length=20)),
                ('publisher', models.CharField(max_length=150)),
                ('no_of_copies', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('lock_period', models.IntegerField(default=90)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
