# Generated by Django 2.2 on 2023-01-12 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='notes',
            new_name='address',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_type', models.CharField(choices=[('BORROW', 'Borrow'), ('RENEW', 'Renew')], default='BORROW', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('books', models.ManyToManyField(related_name='transactions', to='books.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
