# Generated by Django 2.2 on 2023-01-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230113_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='address',
            new_name='notes',
        ),
    ]
