# Generated by Django 2.2 on 2023-01-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230113_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('BORROWED', 'Borrowed'), ('RENEWED', 'Renewed'), ('RETURNED', 'Returned'), ('ABSCONDED', 'Absconded')], default='BORROWED', max_length=10),
        ),
    ]
